### ISSUE TITLE
Experiencing issue when integrating with Facebook

### ISSUE THREAD

**Issue by farhans72** [watson-developer-cloud/botkit-middleware#17]
Hi I tried to integrate my watson conversation workspace with the botkit-middleware using Facebook as Messenger channel. The application crashes with the following error logs; whenever, I ask query for watson conversation.
```
API/2
App instance exited with guid 9e880f86-6d7c-4df6-a9bf-eed53ab35d71 payload: {"cc_partition"=>"default", "droplet"=>"9e880f86-6d7c-4df6-a9bf-eed53ab35d71", "version"=>"805409bf-3a43-4f18-bf60-8b93dd732ea0", "instance"=>"9e30a7d9fb6c48058d4a0a37410d9d6d", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1479201318}
2016-11-15T13:15:18.717+0400
App/0
npm ERR! npm bugs fs-CognitApp
2016-11-15T13:15:18.554+0400
App/0
npm ERR! /home/vcap/app/npm-debug.log
2016-11-15T13:15:18.562+0400
App/0
npm ERR! Please include the following file with any support request:
2016-11-15T13:15:18.562+0400
App/0
npm ERR! npm owner ls fs-CognitApp
2016-11-15T13:15:18.555+0400
App/0
npm ERR! There is likely additional logging output above.
2016-11-15T13:15:18.555+0400
App/0
npm ERR!
2016-11-15T13:15:18.555+0400
App/0
npm ERR! Or if that isn't available, you can get their info via:
2016-11-15T13:15:18.555+0400
App/0
npm ERR! This is most likely a problem with the fs-CognitApp package,
2016-11-15T13:15:18.554+0400
App/0
npm ERR! Tell the author that this fails on your system:
2016-11-15T13:15:18.554+0400
App/0
npm ERR! You can get information on how to open an issue for this project with:
2016-11-15T13:15:18.554+0400
App/0
npm ERR! not with npm itself.
2016-11-15T13:15:18.554+0400
App/0
npm ERR! node server.js
2016-11-15T13:15:18.554+0400
App/0
npm ERR! Failed at the fs-CognitApp@0.0.1 start script 'node server.js'.
2016-11-15T13:15:18.554+0400
App/0
npm ERR! Exit status 2
2016-11-15T13:15:18.553+0400
App/0
npm ERR!
2016-11-15T13:15:18.553+0400
App/0
npm ERR! fs-CognitApp@0.0.1 start: `node server.js`
2016-11-15T13:15:18.553+0400
App/0
npm ERR! code ELIFECYCLE
2016-11-15T13:15:18.553+0400
App/0
npm ERR! npm v2.15.9
2016-11-15T13:15:18.553+0400
App/0
npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
2016-11-15T13:15:18.552+0400
App/0
at Promise._resolveCallback (/home/vcap/app/node_modules/botkit-middleware-watson/node_modules/bluebird/js/release/promise.js:431:57)
2016-11-15T13:15:18.513+0400
App/0
at Promise._settlePromise0 (/home/vcap/app/node_modules/botkit-middleware-watson/node_modules/bluebird/js/release/promise.js:612:10)
2016-11-15T13:15:18.513+0400
App/0
at Promise._settlePromise (/home/vcap/app/node_modules/botkit-middleware-watson/node_modules/bluebird/js/release/promise.js:567:18)
2016-11-15T13:15:18.513+0400
App/0
at tryCatcher (/home/vcap/app/node_modules/botkit-middleware-watson/node_modules/bluebird/js/release/util.js:16:23)
2016-11-15T13:15:18.513+0400
App/0
at Promise._fulfill (/home/vcap/app/node_modules/botkit-middleware-watson/node_modules/bluebird/js/release/promise.js:636:18)
2016-11-15T13:15:18.513+0400
App/0
at Promise._settlePromiseFromHandler (/home/vcap/app/node_modules/botkit-middleware-watson/node_modules/bluebird/js/release/promise.js:510:31)
2016-11-15T13:15:18.513+0400
App/0
at Object.bot.findConversation (/home/vcap/app/node_modules/botkit/lib/Facebook.js:103:13)
2016-11-15T13:15:18.513+0400
App/0
at /home/vcap/app/node_modules/botkit/lib/CoreBot.js:862:21
2016-11-15T13:15:18.513+0400
App/0
at /home/vcap/app/node_modules/botkit/node_modules/ware/node_modules/wrap-fn/index.js:121:18
2016-11-15T13:15:18.513+0400
App/0
at Promise._settlePromises (/home/vcap/app/node_modules/botkit-middleware-watson/node_modules/bluebird/js/release/promise.js:691:18)
2016-11-15T13:15:18.513+0400
App/0
Fatal TypeError: Cannot read property 'output' of undefined
2016-11-15T13:15:18.513+0400
App/0
at Object.Botkit.botkit.trigger (/home/vcap/app/node_modules/botkit/lib/CoreBot.js:779:49)
2016-11-15T13:15:18.513+0400
App/0
at next (/home/vcap/app/node_modules/botkit/node_modules/ware/lib/index.js:82:27)
2016-11-15T13:15:18.513+0400
App/0
at /home/vcap/app/node_modules/botkit-middleware-watson/lib/middleware/index.js:107:9
2016-11-15T13:15:18.513+0400
App/0
at /home/vcap/app/node_modules/botkit/lib/CoreBot.js:866:32
2016-11-15T13:15:18.513+0400
App/0
at Object.<anonymous> (/home/vcap/app/bot-facebook.js:26:40)
2016-11-15T13:15:18.513+0400
App/0
at Object.<anonymous> (/home/vcap/app/node_modules/botkit/lib/CoreBot.js:753:28)
2016-11-15T13:15:18.513+0400
RTR/1
fs-cognitapp.mybluemix.net - [15/11/2016:09:15:18.311 +0000] "POST /facebook/receive HTTP/1.1" 200 289 2 "-" "-" 192.155.237.115:15111 x_forwarded_for:"66.220.158.100" x_forwarded_proto:"https" vcap_request_id:de47848d-4dcd-4dc8-6242-c56ad13e32ec response_time:0.090544254 app_id:9e880f86-6d7c-4df6-a9bf-eed53ab35d71 x_global_transaction_id:"3446389437"
2016-11-15T13:15:18.402+0400
App/0
Client server listening on port 62408
```

**Comment by germanattanasio** [comment]
Hi @farhans72, Try to run the app with `NODE_DEBUG=request` so that you can debug the http requests

**Comment by stevenoh93** [comment]
@farhans72 Make sure you have all of your credentials in the `.env` file, especially the Conversation credentials. I know you get that kind of error log when you're missing the Conversation credentials. Please let us know if that fixes the problem

**Comment by farhans72** [comment]
Guys,
I made a mistake in copying Conversation credentials in the .env file. I missed first digit of the username. 

It would be great if the toolkit return error with these clues rather than crashing.

**Comment by Praveenkumar1586** [comment]
Can anybody help me in resolving this issue. I getting the below error when i try to start npm using singlebot
> botkit-middleware-watson-simple-example@0.0.1 start C:\Cakeorder\botkit-middleware\examples\simple-bot
> node simple-bot-slack.js

Initializing Botkit v0.6.14
info: ** No persistent storage method specified! Data may be lost when process shuts down.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::5000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at Function.listen (C:\Cakeorder\botkit-middleware\examples\simple-bot\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Cakeorder\botkit-middleware\examples\simple-bot\simple-bot-slack.js:56:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! botkit-middleware-watson-simple-example@0.0.1 start: `node simple-bot-slack.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the botkit-middleware-watson-simple-example@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\praveen.k.raja.kumar\AppData\Roaming\npm-cache\_logs\2018-07-01T07_29_19_368Z-debug.log

**Comment by Naktibalda** [comment]
You have something else running on port 5000.
Maybe it is an instance of simple not that you started earlier.
Kill that process or change the port.
