### ISSUE TITLE
Fatal TypeError: Cannot read property 'output' of undefined

### ISSUE THREAD

**Issue by christiankirsch** [watson-developer-cloud/botkit-middleware#28]
I tried to use the simple-bot (locally) to connect my Watson Conversation service with my Slack channel. I exactly followed the instructions shown in the demo: https://www.youtube.com/watch?v=0rnt54ONtQw_. However I receive an error that the property 'output' could not be read. I double checked that my username and password is correct as indicated in another issue. When I change it to wrong values, the detailed debug output is different.
I then tried to log the `message.watsonData` object to the console before the `bot.reply()` method in line 37. This object was undefined as well.

StackTrace (before I made any changes to the code to log more to the console):
```
Fatal TypeError: Cannot read property 'output' of undefined
    at /Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/simple-bot-slack.js:37:42
    at /Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/botkit-middleware-watson/lib/middleware/index.js:106:9
    at tryCatcher (/Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/chk/dev/playground/watsonConversation/botkit-middleware/examples/simple-bot/node_modules/bluebird/js/release/async.js:17:14)
```

Attached is the detailed debug log with `NODE_DEBUG=request`. I replaced credentials with `*`:
[SlackWatsonConversationBox_trace.txt](https://github.com/watson-developer-cloud/botkit-middleware/files/698645/SlackWatsonConversationBox_trace.txt)

**Comment by germanattanasio** [comment]
@stevenoh93 can you take a look at this please?

**Comment by stevenoh93** [comment]
@christiankirsch thank you for pointing this out. This is fixed with #29. It should be fixed when you update your local package

**Comment by Hemanth2396** [comment]
hello @stevenoh93 even i updated the package  also i am getting same error? how can i rectify it?

**Comment by Naktibalda** [comment]
@Hemanth2396 are you using a latest version of middleware?
Are you checking message.watsonError before bot.reply as in current version of simple-bot [example](https://github.com/watson-developer-cloud/botkit-middleware/blob/master/examples/simple-bot/simple-bot-slack.js#L37-L41)?
