### ISSUE TITLE
Error install botKit

### ISSUE THREAD

**Issue by Rhaniel** [watson-developer-cloud/botkit-middleware#36]
Hello guys, I'm trying to install botkit, but it always gives a bug, could anyone help me?

```
npm install botkit-middleware-watson --save
```

```none

  npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config - -get remote.origin.url 
  npm WARN addRemoteGit 
  npm WARN addRemoteGit at ChildProcess.exithandler (child_process.js:211:12) 
  npm WARN addRemoteGit at emitTwo (events.js:106:13) 
  npm WARN addRemoteGit at ChildProcess.emit (events.js:192:7) 
  npm WARN addRemoteGit at maybeClose (internal/child_process.js:890:16) 
  npm WARN addRemoteGit at Socket. (internal/child_process.js:334:1 1) 
  npm WARN addRemoteGit at emitOne (events.js:96:13) 
  npm WARN addRemoteGit at Socket.emit (events.js:189:7) 
  npm WARN addRemoteGit at Pipe._handle.close [as _onclose] (net.js:501:12) 
  npm WARN addRemoteGit git://github.com/ianwremmel/extend-error.git resetting re mote C:\Users\rcborges\AppData\Roaming\npm-cache_git-remotes\git-github-com-ian wremmel-extend-error-git-024938ae because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url 
  npm WARN addRemoteGit 
  npm WARN addRemoteGit at ChildProcess.exithandler (child_process.js:211:12) 
  npm WARN addRemoteGit at emitTwo (events.js:106:13) 
  npm WARN addRemoteGit at ChildProcess.emit (events.js:192:7) 
  npm WARN addRemoteGit at maybeClose (internal/child_process.js:890:16) 
  npm WARN addRemoteGit at Socket. (internal/child_process.js:334:1 1) 
  npm WARN addRemoteGit at emitOne (events.js:96:13) 
  npm WARN addRemoteGit at Socket.emit (events.js:189:7) 
  npm WARN addRemoteGit at Pipe._handle.close [as _onclose] (net.js:501:12) 
  npm WARN addRemoteGit killed: false, 
  npm WARN addRemoteGit code: 1, 
  npm WARN addRemoteGit signal: null, 
  npm WARN addRemoteGit cmd: 'git -c core.longpaths=true config --get remote.ori gin.url' } 
  npm ERR! git clone --template=C:\Users\rcborges\AppData\Roaming\npm-cache_git-r emotes_templates --mirror git://github.com/ianwremmel/extend-error.git C:\Users \rcborges\AppData\Roaming\npm-cache_git-remotes\git-github-com-ianwremmel-exten d-error-git-024938ae: Cloning into bare repository 'C:\Users\rcborges\AppData\Ro aming\npm-cache_git-remotes\git-github-com-ianwremmel-extend-error-git-024938ae '... 
  npm ERR! git clone --template=C:\Users\rcborges\AppData\Roaming\npm-cache_git-r emotes_templates --mirror git://github.com/ianwremmel/extend-error.git C:\Users \rcborges\AppData\Roaming\npm-cache_git-remotes\git-github-com-ianwremmel-exten d-error-git-024938ae: fatal: unable to connect to github.com: 
  npm ERR! git clone --template=C:\Users\rcborges\AppData\Roaming\npm-cache_git-r emotes_templates --mirror git://github.com/ianwremmel/extend-error.git C:\Users \rcborges\AppData\Roaming\npm-cache_git-remotes\git-github-com-ianwremmel-exten d-error-git-024938ae: github.com[0: 192.30.253.113]: errno=No error 
  npm ERR! git clone --template=C:\Users\rcborges\AppData\Roaming\npm-cache_git-r emotes_templates --mirror git://github.com/ianwremmel/extend-error.git C:\Users \rcborges\AppData\Roaming\npm-cache_git-remotes\git-github-com-ianwremmel-exten d-error-git-024938ae: github.com[1: 192.30.253.112]: errno=No error 
  npm ERR! Windows_NT 6.1.7601 
  npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\rcborges\AppDat a\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" 
  npm ERR! node v7.5.0 
  npm ERR! npm v4.3.0 
  npm ERR! code 128


npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\rc borges\AppData\Roaming\npm-cache_git-remotes_templates --mirror git://github.c om/ianwremmel/extend-error.git C:\Users\rcborges\AppData\Roaming\npm-cache_git- remotes\git-github-com-ianwremmel-extend-error-git-024938ae 
npm ERR! Cloning into bare repository 'C:\Users\rcborges\AppData\Roaming\npm-cac he_git-remotes\git-github-com-ianwremmel-extend-error-git-024938ae'... 
npm ERR! fatal: unable to connect to github.com: 
npm ERR! github.com[0: 192.30.253.113]: errno=No error 
npm ERR! github.com[1: 192.30.253.112]: errno=No error 
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at: 
npm ERR! https://github.com/npm/npm/issues


npm ERR! Please include the following file with any support request: 
npm ERR! C:\Users\rcborges\AppData\Roaming\npm-cache_logs\2017-03-08T15_08_ 13_729Z-debug.log 
```

**Comment by germanattanasio** [comment]
Hey @Rhaniel it seems like you have fixed the issue https://github.com/howdyai/botkit/issues/698
